services:
  web:
    build: .
    container_name: reisepass
    restart: always
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=sqlite:///../instance/app.db
      - FLASK_DEBUG=False
      - WERKZEUGLOG=False
    volumes:
      - ./instance:/app/instance
    depends_on: []
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true  # Use an existing network